# Generated by Django 3.0.5 on 2020-05-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('test', models.IntegerField()),
                ('case', models.IntegerField()),
                ('active', models.IntegerField()),
                ('recover', models.IntegerField()),
                ('casepermillion', models.IntegerField()),
                ('testpermillion', models.IntegerField()),
                ('deathpermillion', models.IntegerField()),
            ],
        ),
    ]
