# Generated by Django 3.0.5 on 2020-05-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='active',
            new_name='active_case',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='recover',
            new_name='recovered',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='deathpermillion',
            new_name='total_death',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='test',
            new_name='total_test',
        ),
        migrations.RemoveField(
            model_name='home',
            name='casepermillion',
        ),
        migrations.RemoveField(
            model_name='home',
            name='testpermillion',
        ),
    ]
