# Generated by Django 3.0.5 on 2020-05-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200502_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='active_case',
        ),
        migrations.RemoveField(
            model_name='home',
            name='case',
        ),
        migrations.RemoveField(
            model_name='home',
            name='recovered',
        ),
        migrations.RemoveField(
            model_name='home',
            name='total_death',
        ),
        migrations.RemoveField(
            model_name='home',
            name='total_test',
        ),
        migrations.AddField(
            model_name='home',
            name='confirmedin_barishal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='confirmedin_chattogram',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='confirmedin_dhaka',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='confirmedin_khulna',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='confirmedin_mymensingh',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='confirmedin_rajshahi',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='confirmedin_rangpur',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='confirmedin_sylhet',
            field=models.IntegerField(null=True),
        ),
    ]
