# Generated by Django 3.0.5 on 2020-05-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200502_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='entry_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
